---
# A LANCER EN TANT QUE ROOT sinon le module n'est pas reconnu
- name: miniCloud vSphere Infra setup
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Include ./vars/*.yml
    include_vars:
      dir: vars
      extensions:
        - 'yaml'
        - 'yml'

  - name: VM Folder setup
    community.vmware.vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ datacenter_name }}"
      folder_name: "{{ folder_name }}"
      parent_folder: Simon
      folder_type: vm
      state: present
      validate_certs: True
    register: vm_folder_creation_result
