---
- name: miniCloud vSphere deploy vm1
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Include ./vars/*.yml
    include_vars:
      dir: vars
      extensions:
        - 'yaml'
        - 'yml'

  - name: "Deploy vm : {{ vm_name }}"
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      port: 443
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ datacenter_name }}/vm/Simon/{{ folder_name }}"

      name: "{{ vm_name }}"
      template: "{{ template_name }}"
      state: present
      validate_certs: True
      hardware:
        memory_mb: 8192
        num_cpus: 4
#     disk:
#       - type: thin
#         datastore: "{{ datastore }}"
#         size_gb: 15


  - name: vm PowerOn
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      port: 443
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ datacenter_name }}/vm/Simon/miniCloud-test"
      name: "{{ vm_name }}"
      state: poweredon
      validate_certs: True

