apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  namespace: awx
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: awx
    name: postgres-awx-test-postgres-0
  nfs:
    server: 192.168.1.40
    path: "/export/volumes/postgres"
  volumeMode: Filesystem
