---
# A LANCER EN TANT QUE ROOT sinon le module n'est pas reconnu
- name: miniCloud vSphere Infra setup
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:

  - name: VM Folder setup
    community.vmware.vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ datacenter_name }}"
      folder_name: miniCloud-test
      parent_folder: Simon
      folder_type: vm
      state: present
      # TO DO : Utiliser les certificats
      validate_certs: False
    environment:
      REQUESTS_CA_BUNDLE: /home/trux/miniCloud/vSphereLab1/certs/lin/30e621d5.crt
    register: vm_folder_creation_result
