---
- name: miniCloud vSphere Cleanup
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Include ./vars/*.yml
    include_vars:
      dir: vars
      extensions:
        - 'yaml'
        - 'yml'

  - name: "Cleanup of VM : {{ vm_name }}"
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      port: 443
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ datacenter_name }}/vm/Simon/{{ folder_name }}"
      name: "{{ vm_name }}"
      state: absent
      force: true
      validate_certs: False 

  - name: "Delete folder : {{ folder_name }}"
    community.vmware.vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ datacenter_name }}"
      folder_name: "{{ folder_name }}"
      parent_folder: Simon
      folder_type: vm
      state: absent
      # TO DO : Utiliser les certificats
      validate_certs: False
 
