- hosts: ControlPlane
#  remote_user: kube
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=192.168.128.0/17
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

#   - name: copies calico tigera-operator.yaml
#     get_url:
#       url: https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
#       dest: /tmp/tigera-operator.yaml
#     tags:
#       - tigera


#   - name: modifies pod network ip range in calico-custom-resources.yaml
#     lineinfile:
#       dest: /tmp/tigera-operator.yaml
#       regexp: 'cidr:'
#       line: '      cidr: 192.168.2.0/24'

    - name: copies calico custom-resources.yaml
      get_url:
        url: https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
        dest: /tmp/calico-custom-resources.yaml

    - name: modifies pod network ip range in calico-custom-resources.yaml
      lineinfile:
        dest: /tmp/calico-custom-resources.yaml
        regexp: 'cidr:'
        line: '      cidr: 192.168.128.0/17'

    - name: install Pod network
      become: yes
      become_user: kube
      shell: |
              kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
              kubectl create -f /tmp/calico-custom-resources.yaml
             # kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: kube
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Kubernetes Join command
      ansible.builtin.debug:
        var: kubernetes_join_command.stdout

    - name: Copy join command to localhost in /tmp
      local_action:
        module: copy
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: "/tmp/kubernetes_join_command" 
        mode: "0777"
