- hosts: "ControlPlane,Workers"
  become: yes
#  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Install firewalld and keep up to date
      dnf:
        name: firewalld
        state: latest

    - name: Having it started and enabled
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: activating masquerade on all nodes
      firewalld:
        zone: public
        masquerade: yes
        permanent: true
        state: enabled

    - name: opening ports for all nodes
      firewalld:
        zone: public
        port: '{{ item }}'
        permanent: true
        state: enabled
      loop:
        - 179/tcp
        - 4789/udp
        - 5473/tcp
        - 8472/udp
        - 10250/tcp
        - 10255/tcp
        - 30000-32767/tcp

    - name: Control Plane - opening specific ports
      when: inventory_hostname in groups['ControlPlane']
      firewalld:
        zone: public
        port: '{{ item }}'
        permanent: true
        state: enabled
      loop:
        - 443/tcp
        - 6443/tcp
        - 2379-2380/tcp
        - 10251-10252/tcp
        - 10257/tcp
        - 10259/tcp
        - 8001/tcp
        - 8080/tcp

#   - name: Working Nodes - opening specific ports
#     when: inventory_hostname in groups['Workers']
#     firewalld:
#       zone: public
#       port: '{{ item }}'
#       permanent: true
#       state: enabled
#     loop:
#       - 10250/tcp

    - name: Retart firewalld
      service:
        name: firewalld
        state: restarted
